import type { SubjectSlug } from "@/content/lessonTypes";

export interface VideoLesson {
  id: string;
  youtubeId: string;
  title: string;
  channel: string;
  subjectSlug: SubjectSlug;
  syllabusCodes: string[];
  topicSlug?: string;
  justification: string;
  verifiedAt: string;
}

/**
 * Curadoria inicial de videoaulas do YouTube, pesquisada em 2026-08-19/20 para os 39 codigos do
 * Anexo IV (ver pesquisa/aulas_youtube/ na raiz do projeto para o relatorio completo de cobertura
 * e metodologia). Todas as URLs foram verificadas como reais (nenhuma inventada); a duracao e data
 * de publicacao de parte do acervo nao puderam ser confirmadas pelas ferramentas disponiveis na
 * pesquisa original e por isso nao estao modeladas aqui.
 */
const VERIFIED_AT = "2026-08-20";

export const VIDEO_LESSONS: VideoLesson[] = [
  { id: "video-pt-01-1", youtubeId: "ptbiYTNF_i4", title: `COMPREENSÃO e INTERPRETAÇÃO de textos de gêneros variados [CONCURSOS]`, channel: `Prof. Thiago Charme`, subjectSlug: "portugues", syllabusCodes: ["PT-01"], topicSlug: "pt-01-compreensao-textos", justification: `O título replica quase literalmente o código PT-01 e o canal é voltado a concursos; aula central para compreensão/interpretação de textos de diferentes gêneros, cobrindo a base teórica cobrada pela Cesgranrio.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-01-2", youtubeId: "6lFopVUhNJA", title: `Interpretação de textos para diversos concursos / tipologia textual / treinamento com 13 questões`, channel: `Décio Terror`, subjectSlug: "portugues", syllabusCodes: ["PT-01"], topicSlug: "pt-01-compreensao-textos", justification: `Treina 13 questões de interpretação e tipologia textual aplicáveis a diversos concursos, complementando a teoria com prática de banca.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-01-3", youtubeId: "mxJ3Ml1JBt8", title: `Revisão de Tipos e Gêneros Textuais para concursos | Professora Mariana Noleto`, channel: `OS PEDAGÓGICOS`, subjectSlug: "portugues", syllabusCodes: ["PT-01"], topicSlug: "pt-01-compreensao-textos", justification: `[Duração confirmada 2026-08-20 por inspeção direta: 50min33s.] Aula de revisão específica sobre tipos e gêneros textuais voltada a concursos, útil para reforço rápido antes da prova.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-02-4", youtubeId: "ljQTBylchVo", title: `PORTUGUÊS PARA CONCURSOS 2024: ORTOGRAFIA OFICIAL`, channel: `Nova Concursos`, subjectSlug: "portugues", syllabusCodes: ["PT-02"], topicSlug: "pt-02-ortografia-oficial", justification: `Aula de canal de concursos dedicada inteiramente à ortografia oficial, cobrindo regras de grafia cobradas em provas, alinhada ao código PT-02.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-02-5", youtubeId: "H-QUPE-GY4Q", title: `ORTOGRAFIA OFICIAL | LÍNGUA PORTUGUESA | IBFC | CORREIOS 2024`, channel: `Focus Concursos`, subjectSlug: "portugues", syllabusCodes: ["PT-02"], topicSlug: "pt-02-ortografia-oficial", justification: `Aprofunda a ortografia oficial a partir do padrão de banca IBFC (Correios 2024), ampliando o repertório de regras além do aulão introdutório.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-02-6", youtubeId: "xD5NDLCUhaU", title: `ORTOGRAFIA - Palavras que MAIS CAEM em CONCURSO`, channel: `Prof. Álvaro Ferreira`, subjectSlug: "portugues", syllabusCodes: ["PT-02"], topicSlug: "pt-02-ortografia-oficial", justification: `[Duração confirmada 2026-08-20 por inspeção direta: 1h27min51s — vídeo mais longo do que o esperado para um papel de 'revisão', mas conteúdo consistente com o título.] Revisão objetiva das palavras de grafia mais cobradas em concursos, boa para memorização rápida antes da prova.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-03-7", youtubeId: "60wyY63Lz0k", title: `Aula completa sobre COESÃO TEXTUAL (teoria e questões)`, channel: `Aucielly Nobre`, subjectSlug: "portugues", syllabusCodes: ["PT-03"], topicSlug: "pt-03-coesao-textual", justification: `Aula completa combinando teoria e questões sobre coesão textual, cobrindo os principais mecanismos coesivos exigidos no código PT-03.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-03-8", youtubeId: "LTRVEq2u3zg", title: `AULA: MECANISMOS DE COESÃO TEXTUAL + ESTRUTURA ORGANIZACIONAL - CONCURSO IBGE`, channel: `Faculdade de Ilhéus Oficial`, subjectSlug: "portugues", syllabusCodes: ["PT-03"], topicSlug: "pt-03-coesao-textual", justification: `Aprofunda os mecanismos de coesão associando-os à estrutura organizacional do texto, com recorte de concurso (IBGE), ampliando a análise além do básico.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-03-9", youtubeId: "DKeV0lUyVqY", title: `CEBRASPE - DOMÍNIO DOS MECANISMOS DE COESÃO TEXTUAL`, channel: `Professor Mazziotti`, subjectSlug: "portugues", syllabusCodes: ["PT-03"], topicSlug: "pt-03-coesao-textual", justification: `Foca na resolução de questões de bancas no padrão Cebraspe sobre coesão textual, treinando a aplicação prática do conteúdo.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-04-10", youtubeId: "ltrzPijgKi4", title: `MORFOLOGIA: CLASSES DE PALAVRAS (Para Concurso)`, channel: `Prof. Álvaro Ferreira`, subjectSlug: "portugues", syllabusCodes: ["PT-04"], topicSlug: "pt-04-classes-palavras", justification: `Aula central sobre as dez classes de palavras (morfologia) voltada especificamente a concursos, cobrindo a base teórica do código PT-04.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-04-11", youtubeId: "jX5PkKEsEX8", title: `CLASSE DE PALAVRAS para concurso público em 5 minutos`, channel: `Prof. Álvaro Ferreira`, subjectSlug: "portugues", syllabusCodes: ["PT-04"], topicSlug: "pt-04-classes-palavras", justification: `[Duração confirmada 2026-08-20 por inspeção direta: 5min22s — o título promete '5 minutos', mas o vídeo real tem 5min22s, ligeiramente acima disso; ainda assim é um vídeo curto e objetivo, coerente com o papel de revisão rápida.] Revisão rápida e objetiva das classes de palavras, útil para reforço de véspera de prova.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-04-12", youtubeId: "1xgcSGTyvj4", title: `AULA 01 - MORFOLOGIA || QUESTÕES`, channel: `Professor Fábio Almeida`, subjectSlug: "portugues", syllabusCodes: ["PT-04"], topicSlug: "pt-04-classes-palavras", justification: `Aula orientada à resolução de questões de morfologia/classes de palavras, complementando a teoria com prática de banca.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-05-13", youtubeId: "jdqhnVUvqOc", title: `CONCORDÂNCIA VERBAL - Teoria e Questões para Concurso`, channel: `Prof. Álvaro Ferreira`, subjectSlug: "portugues", syllabusCodes: ["PT-05"], topicSlug: "pt-05-concordancia", justification: `Aula central combinando teoria e questões de concordância verbal, base direta para o código PT-05 (concordância nominal e verbal).`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-05-14", youtubeId: "kFVQOkfV9sk", title: `QUESTÕES COMENTADAS de CONCORDÂNCIA VERBAL e NOMINAL [Prof. Eliane Vieira]`, channel: `Rota de Estudo`, subjectSlug: "portugues", syllabusCodes: ["PT-05"], topicSlug: "pt-05-concordancia", justification: `Questões comentadas cobrindo tanto concordância verbal quanto nominal, treinando aplicação de regras em itens de prova.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-05-15", youtubeId: "C8JPK8vBfa0", title: `Você ainda erra CONCORDÂNCIA VERBAL e NOMINAL? Veja isto antes da prova...`, channel: `Prof. Álvaro Ferreira`, subjectSlug: "portugues", syllabusCodes: ["PT-05"], topicSlug: "pt-05-concordancia", justification: `Revisão de véspera de prova focada nos erros mais comuns de concordância verbal e nominal.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-06-16", youtubeId: "TD8u-10HtyE", title: `Concurso Caixa - Aula de Língua portuguesa: Emprego do sinal indicativo de crase`, channel: `Qconcursos`, subjectSlug: "portugues", syllabusCodes: ["PT-06"], topicSlug: "pt-06-crase", justification: `Aula central sobre o emprego do sinal indicativo de crase produzida por canal de concursos (Qconcursos) para outro edital bancário, cobrindo integralmente o código PT-06.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-06-17", youtubeId: "bf70DXjYjZ4", title: `Emprego do sinal indicativo de Crase - 10 questões de 2024 comentadas`, channel: `Matérias para concursos`, subjectSlug: "portugues", syllabusCodes: ["PT-06"], topicSlug: "pt-06-crase", justification: `Resolve 10 questões recentes (2024) sobre crase, treinando a identificação do sinal indicativo em contextos de prova real.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-06-18", youtubeId: "a3fOIj1E25I", title: `Crase - O motivo do uso do sinal indicativo de crase - FGV - Prof. Robson Teixeira`, channel: `Fazendo a Base`, subjectSlug: "portugues", syllabusCodes: ["PT-06"], topicSlug: "pt-06-crase", justification: `Aprofunda o motivo linguístico do uso da crase (regência + artigo) no padrão da banca FGV, indo além da regra decorada.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-07-19", youtubeId: "G8Stjzy-87k", title: `PONTUAÇÃO - Aulão completo para Concurso Público!`, channel: `Prof. Álvaro Ferreira`, subjectSlug: "portugues", syllabusCodes: ["PT-07"], topicSlug: "pt-07-pontuacao", justification: `Aulão completo sobre todos os sinais de pontuação cobrados em concurso público, correspondendo diretamente ao código PT-07.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-07-20", youtubeId: "KD2TAJyZECc", title: `PONTUAÇÃO FÁCIL: Aprenda o Emprego dos Sinais de Pontuação (Concursos e Vestibulares)`, channel: `Português sem Enrolação (Professora Lis)`, subjectSlug: "portugues", syllabusCodes: ["PT-07"], topicSlug: "pt-07-pontuacao", justification: `Detalha o emprego de cada sinal de pontuação com explicações adicionais voltadas a concursos e vestibulares, aprofundando casos de uso.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-07-21", youtubeId: "k_VdVCK8tSU", title: `CEBRASPE - EMPREGO DOS SINAIS DE PONTUAÇÃO: APRENDA A USAR A VÍRGULA.`, channel: `Professor Mazziotti`, subjectSlug: "portugues", syllabusCodes: ["PT-07"], topicSlug: "pt-07-pontuacao", justification: `Foca na aplicação da vírgula e demais sinais em questões no padrão Cebraspe, treinando o raciocínio de prova.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-08-22", youtubeId: "MavYAYVFG1Y", title: `SEMÂNTICA - sinônimos, antônimos, homônimos, parônimos, hipônimos e hiperônimos`, channel: `Nota Dez Play`, subjectSlug: "portugues", syllabusCodes: ["PT-08"], topicSlug: "pt-08-significacao-palavras", justification: `Aula mais completa sobre significação das palavras, cobrindo sinônimos, antônimos, homônimos, parônimos, hipônimos e hiperônimos — todo o escopo do código PT-08.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-08-23", youtubeId: "jXgaKQZDb_M", title: `SINÔNIMO E ANTÔNIMO || Teoria + Questões de Concurso`, channel: `Prof. Álvaro Ferreira`, subjectSlug: "portugues", syllabusCodes: ["PT-08"], topicSlug: "pt-08-significacao-palavras", justification: `Combina teoria com questões de concurso sobre sinônimos e antônimos, reforçando a aplicação prática do conteúdo semântico.`, verifiedAt: VERIFIED_AT },
  { id: "video-pt-08-24", youtubeId: "ikYBuvJ5ESQ", title: `Significação das Palavras - Aula 01 (Sinônimos e Antônimos)`, channel: `Prof. Wilson Rochenbach`, subjectSlug: "portugues", syllabusCodes: ["PT-08"], topicSlug: "pt-08-significacao-palavras", justification: `Aula de revisão introdutória sobre significação das palavras, retomando de forma direta sinônimos e antônimos.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-02-25", youtubeId: "aCjc5HAy3_M", title: `Matemática básica - Razão, proporção, regra de três e porcentagem`, channel: `Professor Julio Cesar | Bizutemática`, subjectSlug: "matematica", syllabusCodes: ["MAT-02"], topicSlug: "mat-02-razao-proporcao", justification: `Aula central que reúne razão, proporção, regra de três e porcentagem em uma única explicação, cobrindo todo o escopo do código MAT-02.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-02-26", youtubeId: "_QEsLci2UOo", title: `Razão, Proporção, Regra de Três e Porcentagem na Prova de Matemática do Encceja (Aula 4 de 5)`, channel: `Matemática Rio (Prof. Rafael Procópio)`, subjectSlug: "matematica", syllabusCodes: ["MAT-02"], topicSlug: "mat-02-razao-proporcao", justification: `Aprofunda o tema no contexto de prova oficial (Encceja), detalhando regra de três composta e casos de porcentagem mais elaborados.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-02-27", youtubeId: "qwjXCnlPcJU", title: `Matemática para quem tem dificuldade - Regra de três simples com porcentagem - questão de concurso`, channel: `André Simão`, subjectSlug: "matematica", syllabusCodes: ["MAT-02"], topicSlug: "mat-02-razao-proporcao", justification: `Resolve passo a passo uma questão real de concurso envolvendo regra de três simples com porcentagem.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-03-28", youtubeId: "J841jAJwY9M", title: `Matemática | Funções Afim, Exponencial, Logarítmica, Quadrática e Trigonométrica`, channel: `Editora BP no Enem`, subjectSlug: "matematica", syllabusCodes: ["MAT-03"], topicSlug: "mat-03-funcoes", justification: `Aula central que percorre os principais tipos de função cobrados no código MAT-03: afim/polinomial, exponencial, logarítmica e trigonométrica.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-03-29", youtubeId: "ZyRw3xjrx3c", title: `CNU - Bloco 8 - Aula de Matemática: Funções: afins, quadráticas, exponenciais, logarítmicas.`, channel: `Qconcursos`, subjectSlug: "matematica", syllabusCodes: ["MAT-03"], topicSlug: "mat-03-funcoes", justification: `Aprofunda funções afins, quadráticas, exponenciais e logarítmicas no contexto de concurso público (CNU), com aplicação a itens de prova.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-03-30", youtubeId: "Dg0_S0_wa-U", title: `funções exponenciais e logarítmicas - revisão ESA`, channel: `Matemática Passo a Passo!`, subjectSlug: "matematica", syllabusCodes: ["MAT-03"], topicSlug: "mat-03-funcoes", justification: `Revisão objetiva de funções exponenciais e logarítmicas voltada a prova, útil para reforço de véspera.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-04-31", youtubeId: "h_8abJwkqoc", title: `Matemática para concursos | Equação do 1º e 2º grau e equação exponencial com André Arruda`, channel: `Gran Cursos Online`, subjectSlug: "matematica", syllabusCodes: ["MAT-04"], topicSlug: "mat-04-equacoes", justification: `Aula de canal consolidado de concursos (Gran Cursos) cobrindo equações do 1º e 2º grau e equações exponenciais, núcleo do código MAT-04.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-04-32", youtubeId: "fRQvZsTkWsQ", title: `SISTEMA EQ. DO 1º GRAU - 6 QUESTÕES CONCURSO`, channel: `Professor em Casa (Felipe Cardoso)`, subjectSlug: "matematica", syllabusCodes: ["MAT-04"], topicSlug: "mat-04-equacoes", justification: `Resolve 6 questões de concurso sobre sistemas de equações do 1º grau, complementando a teoria com prática de prova.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-04-33", youtubeId: "0dg1vXFSee8", title: `Equações de 1º e 2º graus | Concursos VUNESP`, channel: `Contate a Matemática`, subjectSlug: "matematica", syllabusCodes: ["MAT-04"], topicSlug: "mat-04-equacoes", justification: `Revisão de equações de 1º e 2º grau no padrão da banca VUNESP, útil para reforço direcionado a concursos dessa banca.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-05-34", youtubeId: "_8mZOSXCRp8", title: `ANÁLISE COMBINATÓRIA | PERMUTAÇÃO | ARRANJO | COMBINAÇÃO`, channel: `Dicasdemat Sandro Curiós`, subjectSlug: "matematica", syllabusCodes: ["MAT-05"], topicSlug: "mat-05-analise-combinatoria", justification: `Aula central que cobre permutação, arranjo e combinação, os três pilares de contagem do código MAT-05.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-05-35", youtubeId: "x3fpYbJ2N7M", title: `Análise Combinatória - Princípio Fundamental da Contagem - Prof. Gui`, channel: `Matemática em Exercícios`, subjectSlug: "matematica", syllabusCodes: ["MAT-05"], topicSlug: "mat-05-analise-combinatoria", justification: `Aprofunda especificamente o princípio fundamental da contagem (multiplicativo), base conceitual antes de arranjos e combinações.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-05-36", youtubeId: "lJLMHFqrn4c", title: `APRENDA COM EXERCÍCIOS | ANÁLISE COMBINATÓRIA`, channel: `Dicasdemat Sandro Curiós`, subjectSlug: "matematica", syllabusCodes: ["MAT-05"], topicSlug: "mat-05-analise-combinatoria", justification: `Foca na resolução de exercícios de análise combinatória, treinando a aplicação prática dos conceitos de contagem.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-06-37", youtubeId: "0_PhBIUpD7w", title: `Probabilidade em espaços amostrais equiprováveis`, channel: `Kuadro Oficial`, subjectSlug: "matematica", syllabusCodes: ["MAT-06"], topicSlug: "mat-06-probabilidade", justification: `Aula central sobre probabilidade em espaços amostrais equiprováveis, correspondendo diretamente ao código MAT-06.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-06-38", youtubeId: "ijnrJR8Besg", title: `Probabilidade - Probabilidade em espaço amostral finito e equiprovável - Aula 72`, channel: `Portal da Matemática OBMEP`, subjectSlug: "matematica", syllabusCodes: ["MAT-06"], topicSlug: "mat-06-probabilidade", justification: `Aprofunda a formalização de espaço amostral finito e equiprovável, com abordagem mais rigorosa do que a aula introdutória.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-06-39", youtubeId: "6IxBMhpOm20", title: `Aprenda Probabilidade para Concursos Públicos - Aula 1`, channel: `Felippe Loureiro`, subjectSlug: "matematica", syllabusCodes: ["MAT-06"], topicSlug: "mat-06-probabilidade", justification: `Introduz probabilidade com foco declarado em concursos públicos, trazendo exemplos e questões aplicadas ao formato de prova.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-07-40", youtubeId: "1ZEPQ1glJME", title: `Estatística (Média, Mediana, Moda, Variância e Desvio Padrão) - Prof. Gui`, channel: `Matemática em Exercícios`, subjectSlug: "matematica", syllabusCodes: ["MAT-07"], topicSlug: "mat-07-estatistica", justification: `Aula central que cobre as principais medidas de estatística descritiva do código MAT-07: média, mediana, moda, variância e desvio padrão.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-07-41", youtubeId: "l2MyLvp82Rg", title: `[ESTATÍSTICA] Médias, Moda, Mediana, Variância e Desvio-Padrão [ENEM/CONCURSO]`, channel: `Exatas Com Vagner Lopes`, subjectSlug: "matematica", syllabusCodes: ["MAT-07"], topicSlug: "mat-07-estatistica", justification: `Aprofunda as mesmas medidas estatísticas com foco explícito em ENEM/concurso, trazendo variações de tipos de média.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-07-42", youtubeId: "-q7X1K1Dcms", title: `EXERCÍCIO: MODA, MEDIANA, MÉDIA, DESVIO PADRÃO E VARIÂNCIA || ESTATÍSTICA DESCRITIVA`, channel: `Kassa Student`, subjectSlug: "matematica", syllabusCodes: ["MAT-07"], topicSlug: "mat-07-estatistica", justification: `Resolve exercício completo partindo de tabela de frequência, treinando o cálculo de todas as medidas do código MAT-07.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-08-43", youtubeId: "YExQ10soiJg", title: `Matemática Financeira - Aula 1 - Juros Simples e Compostos - Prof. Gui`, channel: `Matemática em Exercícios`, subjectSlug: "matematica", syllabusCodes: ["MAT-08"], topicSlug: "mat-08-matematica-financeira", justification: `Aula central que introduz juros simples e compostos, cobrindo montante, taxa e tempo conforme o código MAT-08.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-08-44", youtubeId: "LbUhrTjgnC0", title: `Aula 01 - Capital, Juro, Taxa de Juros e Montante`, channel: `Professor Willian Capriata`, subjectSlug: "matematica", syllabusCodes: ["MAT-08"], topicSlug: "mat-08-matematica-financeira", justification: `Aprofunda as definições formais de capital, juro, taxa de juros e montante antes de aplicar as fórmulas de juros simples/compostos.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-08-45", youtubeId: "bz8YdaD6Co0", title: `Aula 03 - Exercícios de fixação - Juros simples e compostos`, channel: `Professor Willian Capriata`, subjectSlug: "matematica", syllabusCodes: ["MAT-08"], topicSlug: "mat-08-matematica-financeira", justification: `Aula de exercícios de fixação sobre juros simples e compostos, mesma série do vídeo de aprofundamento, treinando o cálculo do montante.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-09-46", youtubeId: "Ay5uvMhZqc8", title: `Geometria Plana - Aula 6 - Relações Métricas no Triângulo Retângulo - Prof. Gui`, channel: `Matemática em Exercícios`, subjectSlug: "matematica", syllabusCodes: ["MAT-09"], topicSlug: "mat-09-geometria-plana", justification: `Aula central sobre relações métricas no triângulo retângulo, núcleo teórico citado explicitamente no código MAT-09.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-09-47", youtubeId: "Sk4KxSLUrZc", title: `Relações Métricas no Triângulo Retângulo (Demonstração e Exercícios) - GEOMETRIA PLANA (Aula 13)`, channel: `Equaciona Com Paulo Pereira`, subjectSlug: "matematica", syllabusCodes: ["MAT-09"], topicSlug: "mat-09-geometria-plana", justification: `Aprofunda com a demonstração formal das relações métricas, indo além da aplicação direta de fórmulas.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-09-48", youtubeId: "CZaNGDeInSU", title: `GEOMETRIA PLANA - TRIÂNGULO RETÂNGULO`, channel: `Prof. Sérgio Mendes`, subjectSlug: "matematica", syllabusCodes: ["MAT-09"], topicSlug: "mat-09-geometria-plana", justification: `[CONFIRMADO 2026-08-20 por inspeção da página: descrição completa do vídeo diz literalmente 'Curso Preparatório Online e Gratuito de MATEMÁTICA BÁSICA e GEOMETRIA PLANA com exercícios resolvidos para o Ensino Fundamental, Médio e Superior, ENEM, Vestibulares e Concursos Públicos' — confirma resolução de exercícios.] Aula orientada a exercícios sobre triângulo retângulo e Teorema de Pitágoras, com foco declarado em concursos.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-10-49", youtubeId: "RGlCdaZJrI4", title: `VOLUME DE SÓLIDOS GEOMÉTRICOS - Prisma, Paralelepípedo, Cubo, Pirâmide, Cilindro e Esfera`, channel: `Gis com Giz`, subjectSlug: "matematica", syllabusCodes: ["MAT-10"], topicSlug: "mat-10-geometria-espacial", justification: `Aula central que percorre o cálculo de volume de todos os principais sólidos geométricos, cobrindo o escopo do código MAT-10.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-10-50", youtubeId: "F1jv-TYaeMk", title: `Geometria Espacial - Aula 01 - Prismas`, channel: `Prof. Reinaldo Amirato`, subjectSlug: "matematica", syllabusCodes: ["MAT-10"], topicSlug: "mat-10-geometria-espacial", justification: `Aprofunda especificamente prismas (classificação, elementos, áreas e volumes), detalhando um dos sólidos do código MAT-10.`, verifiedAt: VERIFIED_AT },
  { id: "video-mat-10-51", youtubeId: "Y_gD7S6OkC4", title: `Geometria Espacial I Revisão Completa`, channel: `Dicasdemat Sandro Curiós`, subjectSlug: "matematica", syllabusCodes: ["MAT-10"], topicSlug: "mat-10-geometria-espacial", justification: `Revisão completa de geometria espacial (prismas, cilindro, pirâmide, cone e esfera), útil para reforço final.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-01-52", youtubeId: "r1xqMjl6bYg", title: `Recrutamento e Seleção - Gestão de Pessoas - Prof. Rodrigo Rennó`, channel: `Rodrigo Rennó`, subjectSlug: "especificas", syllabusCodes: ["AC-01"], topicSlug: "ac-01-recursos-humanos", justification: `Aula do professor Rodrigo Rennó (referência em Administração Geral para concursos, autor de obra usada pelo Estratégia Concursos) dedicada especificamente a Recrutamento e Seleção dentro de Gestão de Pessoas, cobrindo diretamente o primeiro subtema do código AC-01. Escolhida como principal por tratar o tópico de forma central e não superficial.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-01-53", youtubeId: "3Uav1QsTS6o", title: `Gestão por Competências - Aula Completa - Prof. Rodrigo Rennó`, channel: `Rodrigo Rennó`, subjectSlug: "especificas", syllabusCodes: ["AC-01"], topicSlug: "ac-01-recursos-humanos", justification: `Aula completa sobre Gestão por Competências, aprofundando o subtema 'gestão de competências' do AC-01 além do que a aula principal cobre, com o mesmo professor de referência em concursos de Administração.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-01-54", youtubeId: "SkFLvq8jzWA", title: `Aula de Gestão de Pessoas para Concursos - Gestão Estratégica`, channel: `AlfaCon`, subjectSlug: "especificas", syllabusCodes: ["AC-01"], topicSlug: "ac-01-recursos-humanos", justification: `Aula de revisão de Gestão de Pessoas voltada a concursos pelo canal AlfaCon (canal consolidado de concursos), útil para revisar de forma ampla os temas de RH do AC-01 (recrutamento, plano de carreira, desempenho) em formato mais objetivo que as aulas anteriores.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-02-55", youtubeId: "0eQhcFOasS4", title: `Como funciona o Sistema de Gestão Integrada (SGI) na prática?`, channel: `SG4 Gestão Ocupacional`, subjectSlug: "especificas", syllabusCodes: ["AC-02"], topicSlug: "ac-02-sistema-gestao-integrado", justification: `Explica de forma central os princípios de integração de um Sistema de Gestão Integrado (Qualidade, Meio Ambiente, Segurança) na prática, tema direto do código AC-02. Usado após esgotar busca em canais de concursos (ver nota de esgotamento na cobertura).`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-02-56", youtubeId: "D8Uped-KucU", title: `SGI - Sistema de Gestão Integrado - Como funciona o SGI?`, channel: `Improova`, subjectSlug: "especificas", syllabusCodes: ["AC-02"], topicSlug: "ac-02-sistema-gestao-integrado", justification: `Aprofunda o funcionamento do SGI e a integração das normas ISO 9001/14001/45001, complementando a aula principal com outro ângulo sobre o mesmo tema central do AC-02.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-02-57", youtubeId: "3ugSp5E8eAc", title: `Auditoria Interna ISO 9001. Como é uma auditoria interna ou externa ISO 9001 em qualquer empresa`, channel: `Marilis Kuligoski`, subjectSlug: "especificas", syllabusCodes: ["AC-02"], topicSlug: "ac-02-sistema-gestao-integrado", justification: `Cobre especificamente auditorias internas dentro de sistemas de gestão da qualidade, revisando de forma prática o subtema 'auditorias internas e ações corretivas/preventivas' do AC-02, que as duas aulas anteriores não detalham.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-03-58", youtubeId: "z6OHEDUFq94", title: `Administração de Materiais e Patrimônio para Institutos Federais - Prof. Ricardo Campanário`, channel: `Estratégia Concursos`, subjectSlug: "especificas", syllabusCodes: ["AC-03"], topicSlug: "ac-03-administracao-patrimonial", justification: `Aula do canal oficial Estratégia Concursos sobre Administração de Materiais e Patrimônio, cobrindo de forma central classificação, controle e gestão de bens patrimoniais, núcleo do código AC-03.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-03-59", youtubeId: "VTC1jjDyTII", title: `Concurso BNDES - Aula de Administração de Recursos Materiais: Administração Patrimonial`, channel: `Qconcursos`, subjectSlug: "especificas", syllabusCodes: ["AC-03"], topicSlug: "ac-03-administracao-patrimonial", justification: `[CORRIGIDO 2026-08-20 após assistir/inspecionar o vídeo: papel reclassificado de complementar_questoes para complementar_aprofundamento — a descrição completa (verificada via inspeção da página) não menciona resolução de questões; é uma aula ao vivo teórica dentro do curso estruturado 'Concurso BNDES' (132 lições) da Qconcursos, sem foco declarado em prática de itens. Duração e data confirmadas diretamente na página: 37min29s, transmitida ao vivo em 18/09/2024.] Aula do canal Qconcursos preparada para outro edital de empresa pública (BNDES), dedicada especificamente a Administração Patrimonial, aprofundando o tema além do panorama da aula principal (Estratégia Concursos).`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-03-60", youtubeId: "gfNAHDLSYMY", title: `CONCURSO UENP: GESTÃO PATRIMONIAL | CONTROLE DE BENS PÚBLICOS`, channel: `Carranza Cursos`, subjectSlug: "especificas", syllabusCodes: ["AC-03"], topicSlug: "ac-03-administracao-patrimonial", justification: `Aula de revisão recente (2026) sobre gestão patrimonial e controle de bens, preparada para outro concurso público, reforçando de forma objetiva inventário e controle patrimonial do AC-03.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-04-61", youtubeId: "Es8MFjbqGw4", title: `Diferenças da manutenção preventiva, corretiva e preditiva`, channel: `Checklist Fácil (Dando Check)`, subjectSlug: "especificas", syllabusCodes: ["AC-04"], topicSlug: "ac-04-gestao-manutencao", justification: `Explica de forma central e comparativa os três tipos de manutenção (preventiva, corretiva, preditiva) citados literalmente no código AC-04. Usado após esgotar a busca em canais de concursos para este tema técnico (ver esgotamento na cobertura).`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-04-62", youtubeId: "ju8XDZguebs", title: `A diferença entre manutenção corretiva, preventiva e preditiva | Danilo Romão #02`, channel: `Fracttal Brasil`, subjectSlug: "especificas", syllabusCodes: ["AC-04"], topicSlug: "ac-04-gestao-manutencao", justification: `Aprofunda com outro especialista (Danilo Romão) as diferenças práticas entre os tipos de manutenção e sua aplicação industrial, complementando a aula principal com exemplos adicionais.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-04-63", youtubeId: "EfuigH4nI0Y", title: `O que é PCM - Planejamento e Controle da Manutenção?`, channel: `ENGETELES - Escola de Gestão da Manutenção`, subjectSlug: "especificas", syllabusCodes: ["AC-04"], topicSlug: "ac-04-gestao-manutencao", justification: `Cobre especificamente o subtema 'planejamento e controle da manutenção' do AC-04, que as duas aulas anteriores (focadas nos tipos de manutenção) não detalham, funcionando como revisão complementar do conceito de PCM.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-05-64", youtubeId: "RFzZbauQ2xA", title: `Gestão do Desempenho - Administração de Recursos Humanos`, channel: `Rodrigo Rennó`, subjectSlug: "especificas", syllabusCodes: ["AC-05"], topicSlug: "ac-05-gestao-indicadores", justification: `Aula central de Rodrigo Rennó sobre gestão do desempenho, incluindo indicadores de desempenho e sua utilização para acompanhamento e tomada de decisão, núcleo do código AC-05.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-05-65", youtubeId: "Ns47JXmkvWU", title: `Gestão do Desempenho - Aula de questões comentadas do Cespe / Cebraspe`, channel: `Rodrigo Rennó`, subjectSlug: "especificas", syllabusCodes: ["AC-05"], topicSlug: "ac-05-gestao-indicadores", justification: `Aula de questões comentadas de bancas sobre gestão do desempenho e indicadores, permitindo praticar a aplicação do conteúdo da aula principal em formato de prova, complementando com foco em questões.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-05-66", youtubeId: "OH5V8_l1ogQ", title: `Indicadores de Gestão - Eficiência Eficácia e Efetividade - Prof. Rodrigo Rennó`, channel: `Rodrigo Rennó`, subjectSlug: "especificas", syllabusCodes: ["AC-05"], topicSlug: "ac-05-gestao-indicadores", justification: `[SUBSTITUÍDO 2026-08-20: o vídeo original ('Dica nº83', AlfaCon) tinha apenas 0:58 (58 segundos) — curto demais para funcionar como uma aula real, apesar de tecnicamente cobrir o tema. Substituído por este vídeo do mesmo professor de referência da aula principal e da aula de questões deste código, dedicado especificamente à tríade eficiência/eficácia/efetividade — um recorte conceitual específico dentro de 'indicadores de desempenho' que a aula principal não detalha da mesma forma, com duração real e substancial (14min26s), confirmada por inspeção direta.] Aula dedicada aos conceitos de eficiência, eficácia e efetividade dentro da gestão de indicadores de desempenho, aprofundando um recorte conceitual específico do código AC-05.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-06-67", youtubeId: "RNVgJHpOUrA", title: `Juros Simples x Juros Compostos - Aula 1`, channel: `Felippe Loureiro`, subjectSlug: "especificas", syllabusCodes: ["AC-06"], topicSlug: "ac-06-matematica-financeira", justification: `Aula do professor Felippe Loureiro, especializado em matemática e matemática financeira para concursos (inclusive com curso específico para a Transpetro), comparando juros simples e compostos, núcleo do código AC-06.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-06-68", youtubeId: "wmverYTpORw", title: `Aula 1: Matemática Financeira - Desconto Comercial Simples`, channel: `Professor Julio Cesar (Bizutemática)`, subjectSlug: "especificas", syllabusCodes: ["AC-06"], topicSlug: "ac-06-matematica-financeira", justification: `Aprofunda especificamente o subtema 'descontos' do AC-06, que a aula principal (focada em juros) não cobre em detalhe, com um professor dedicado a matemática para concursos.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-06-69", youtubeId: "XpHNly9AjFM", title: `20 Questões Resolvidas de Concursos de Porcentagem - Várias Bancas`, channel: `Matemática Boa`, subjectSlug: "especificas", syllabusCodes: ["AC-06"], topicSlug: "ac-06-matematica-financeira", justification: `Resolução de 20 questões de porcentagem de diferentes bancas, cobrindo o subtema 'porcentagem' do AC-06 em formato de prática de questões, complementando as aulas teóricas anteriores.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-07-70", youtubeId: "E4otkAWeaZc", title: `Princípios da Contabilidade - [Tudo em 24 min]`, channel: `CFC Academy`, subjectSlug: "especificas", syllabusCodes: ["AC-07"], topicSlug: "ac-07-registros-contabeis", justification: `Aula central e completa sobre os princípios/fundamentos contábeis (registro pelo valor original, prudência, competência etc.), tema literal do código AC-07 ('princípios e práticas contábeis fundamentais'), em canal focado em preparação para o exame do CFC.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-07-71", youtubeId: "eOPXQr7MNjU", title: `Os princípios contábeis ainda existem? Características qualitativas fundamentais e de melhoria`, channel: `Professor Quintino`, subjectSlug: "especificas", syllabusCodes: ["AC-07"], topicSlug: "ac-07-registros-contabeis", justification: `Aprofunda a discussão sobre os princípios contábeis frente à estrutura conceitual atual (características qualitativas), complementando a aula principal com uma visão mais atual e crítica do tema.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-07-72", youtubeId: "8nXq_xZiVak", title: `ECF: Tudo sobre a Escrituração Contábil Fiscal (na prática)`, channel: `Contabilidade Facilitada`, subjectSlug: "especificas", syllabusCodes: ["AC-07"], topicSlug: "ac-07-registros-contabeis", justification: `Cobre especificamente o subtema 'obrigações acessórias e controle fiscal' do AC-07 (ECF é uma obrigação acessória concreta), tema não tratado pelas duas aulas anteriores, que focam nos princípios contábeis.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-08-73", youtubeId: "6PzMw91_dHU", title: `Demonstração dos Fluxos de Caixa (DFC) - Método Indireto`, channel: `Marcia Lacerda Farias`, subjectSlug: "especificas", syllabusCodes: ["AC-08"], topicSlug: "ac-08-fluxo-caixa", justification: `Aula central sobre a elaboração da Demonstração dos Fluxos de Caixa pelo método indireto, cobrindo diretamente 'elaboração e análise (direto e indireto)' do código AC-08. Usado após esgotar busca por aula equivalente em canal de concursos (ver esgotamento na cobertura).`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-08-74", youtubeId: "FeD893hNeDY", title: `Demonstração Fluxo de Caixa - Método Direto e Indireto (Balanço Patrimonial e DRE)`, channel: `GCoelho`, subjectSlug: "especificas", syllabusCodes: ["AC-08"], topicSlug: "ac-08-fluxo-caixa", justification: `Aprofunda comparando os métodos direto e indireto e mostrando a integração da DFC com Balanço Patrimonial e DRE, atendendo ao subtema 'integração com orçamento e projeções/demais demonstrações' do AC-08.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-08-75", youtubeId: "JUe5U0JTdws", title: `46 - Demonstração do Fluxo de Caixa - Método Indireto - Contabilidade`, channel: `Professor Quintino`, subjectSlug: "especificas", syllabusCodes: ["AC-08"], topicSlug: "ac-08-fluxo-caixa", justification: `Revisão numerada de uma série de aulas de contabilidade especificamente sobre o método indireto da DFC, reforçando de forma objetiva o conteúdo já visto nas aulas anteriores.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-09-76", youtubeId: "BRaIxtk-rr4", title: `Análise das Demonstrações Contábeis do ZERO para Concursos - Semana Nacional EC`, channel: `Estratégia Concursos`, subjectSlug: "especificas", syllabusCodes: ["AC-09"], topicSlug: "ac-09-balanco-dre", justification: `Aula gratuita do canal oficial Estratégia Concursos (evento 'Semana Nacional'), tratando do zero a análise das demonstrações contábeis, cobrindo a relação entre Balanço Patrimonial, DRE e demais demonstrações, núcleo do código AC-09.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-09-77", youtubeId: "veQVYctnBFM", title: `Balanço Patrimonial e Demonstração do Resultado (DRE): Aula Completa`, channel: `Contabilidade Facilitada`, subjectSlug: "especificas", syllabusCodes: ["AC-09"], topicSlug: "ac-09-balanco-dre", justification: `Aula completa e detalhada sobre a estrutura do Balanço Patrimonial (Ativo, Passivo, PL) e da DRE, aprofundando a montagem de cada demonstração além do panorama da aula principal.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-09-78", youtubeId: "EkNJ8v6T6bQ", title: `Balanço Patrimonial e Demonstração Resultado - Conceitos Básicos em 10 min! Demonstrações Financeiras`, channel: `GCoelho`, subjectSlug: "especificas", syllabusCodes: ["AC-09"], topicSlug: "ac-09-balanco-dre", justification: `Vídeo curto de revisão rápida (10 minutos) dos conceitos básicos de Balanço Patrimonial e DRE, útil para consolidar rapidamente a estrutura das duas demonstrações antes da prova.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-10-79", youtubeId: "-d_nHCLAF4E", title: `Hora da Verdade Petrobras: Logística, Suprimentos, Estoques, Almoxarifados(Suprimento Bens Serviços)`, channel: `Estratégia Concursos`, subjectSlug: "especificas", syllabusCodes: ["AC-10"], topicSlug: "ac-10-logistica-cadeia-suprimentos", justification: `Aula ao vivo completa de revisão para concursos de estatal (Petrobras) cobrindo diretamente logística, cadeia de suprimentos, estoques e almoxarifados; conteúdo extenso e diretamente aplicável ao código, apesar de não ser específico do edital Transpetro 2026.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-10-80", youtubeId: "zDyog0iIRwk", title: `Logística de Transportes - Aula: Fundamentos de Logística (Aula 1) - Concursos Petrobras | CPWS`, channel: `CPWS - Concursos Petrobras e Transpetro`, subjectSlug: "especificas", syllabusCodes: ["AC-10"], topicSlug: "ac-10-logistica-cadeia-suprimentos", justification: `Primeira aula de uma série de 4 sobre fundamentos de logística voltada a concursos de Petrobras/Transpetro; aprofunda conceitos e aplicações de logística e cadeia de suprimentos além de uma introdução.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-10-81", youtubeId: "VTGkFkJcadg", title: `Sprint de Questões Cesgranrio para Transpetro: Monitoramento Logístico - Prof. Daniel Almeida`, channel: `Estratégia Concursos`, subjectSlug: "especificas", syllabusCodes: ["AC-10"], topicSlug: "ac-10-logistica-cadeia-suprimentos", justification: `Sprint de resolução de questões estilo Cesgranrio preparado especificamente para o edital Transpetro 2026, cobrindo o eixo de Monitoramento Logístico (que inclui cadeia de suprimentos); treino de questões objetivas.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-11-82", youtubeId: "547BQhUqAwk", title: `Logística de Transporte - Logística Internacional e Aduaneira (Aula 1): Modais | CPWS Concursos`, channel: `CPWS - Concursos Petrobras e Transpetro`, subjectSlug: "especificas", syllabusCodes: ["AC-11"], topicSlug: "ac-11-modalidades-transporte", justification: `NAO`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-11-83", youtubeId: "9zNR8n7ZAxg", title: `Logística de Transporte - Logística Internacional e Aduaneira (Aula 2): Convenções | CPWS Concursos`, channel: `CPWS - Concursos Petrobras e Transpetro`, subjectSlug: "especificas", syllabusCodes: ["AC-11"], topicSlug: "ac-11-modalidades-transporte", justification: `NAO`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-11-84", youtubeId: "5uhqjQPk76I", title: `Concurso ANTT: Legislação Aplicada a Regulação em Transporte Terrestre - Prof. Nick Simonek`, channel: `Estratégia Concursos`, subjectSlug: "especificas", syllabusCodes: ["AC-11"], topicSlug: "ac-11-modalidades-transporte", justification: `Aula da Estratégia Concursos sobre legislação e regulação de transporte terrestre (foco em concurso ANTT), diretamente aplicável ao subtema 'regulação e legislação do transporte' do código, servindo como revisão do arcabouço normativo.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-12-85", youtubeId: "mFOStDt24Ng", title: `Gestão de estoque: conceito, importância, como fazer, técnicas e benefícios (AULA COMPLETA)`, channel: `SAC Logística`, subjectSlug: "especificas", syllabusCodes: ["AC-12"], topicSlug: "ac-12-gestao-estoques", justification: `Aula completa e didática sobre gestão de estoques (conceito, técnicas, benefícios), cobrindo classificação e métodos de gestão de estoque exigidos pelo código. Usado como principal após não se localizar aula específica e completa sobre o tema nos canais de concursos prioritários (Estratégia Concursos, CPWS) apesar de 3 buscas com termos distintos.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-12-86", youtubeId: "CiFwih4XHNU", title: `Gestão de ESTOQUE usando CURVA ABC (passo a passo)`, channel: `Ser Logístico`, subjectSlug: "especificas", syllabusCodes: ["AC-12"], topicSlug: "ac-12-gestao-estoques", justification: `[Nome do canal corrigido de 'Ser Logística' para 'Ser Logístico' em 2026-08-20, após verificação via oEmbed.] Aprofunda o método de classificação ABC de estoques (critério de classificação e priorização), tema central do código em 'classificação e métodos de gestão'.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-12-87", youtubeId: "J0lRz83b_Go", title: `QUESTÃO DE ESTOQUE - PONTO DE PEDIDO E ESTOQUE DE SEGURANÇA ADMINISTRAÇÃO DE MATERIAIS`, channel: `Joselias Silva`, subjectSlug: "especificas", syllabusCodes: ["AC-12"], topicSlug: "ac-12-gestao-estoques", justification: `Resolução de questão sobre ponto de pedido e estoque de segurança, conceitos diretamente ligados a 'políticas de estoque e níveis de serviço' do código; formato de treino de questão.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-13-88", youtubeId: "JNOfOOTO_Io", title: `TÉCNICAS DE ARMAZENAGEM: Conceito, tipos e importância (Aula completa)`, channel: `SAC Logística`, subjectSlug: "especificas", syllabusCodes: ["AC-13"], topicSlug: "ac-13-armazenagem", justification: `Aula completa sobre conceito, tipos e importância da armazenagem, cobrindo diretamente 'tipos de armazéns e funções' do código. Usado após busca não localizar aula equivalente em Estratégia Concursos, Adriane Fauth (não cobre logística) ou CPWS especificamente sobre tipos/layout de armazém.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-13-89", youtubeId: "9HUSHbV3Vbs", title: `Estruturas de armazenagem logística (AULA COMPLETA)`, channel: `SAC Logística`, subjectSlug: "especificas", syllabusCodes: ["AC-13"], topicSlug: "ac-13-armazenagem", justification: `Aprofunda estruturas físicas de armazenagem (porta-paletes, estruturas verticais etc.), tema de 'tecnologias' e organização de armazéns do código.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-13-90", youtubeId: "UCSUPK_L8wM", title: `Layout da Armazenagem na Logística`, channel: `Canal de Logística`, subjectSlug: "especificas", syllabusCodes: ["AC-13"], topicSlug: "ac-13-armazenagem", justification: `Revisão objetiva e mais curta sobre layout de armazém, cobrindo o subtema 'layout e organização' do código de forma resumida.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-14-91", youtubeId: "BsX4GAKGdgc", title: `EQUIPAMENTOS DE MOVIMENTAÇÃO: Conceito, importância, tipos e características! | Aula Completa`, channel: `SAC Logística`, subjectSlug: "especificas", syllabusCodes: ["AC-14"], topicSlug: "ac-14-manuseio-materiais", justification: `Aula objetiva sobre equipamentos de movimentação de materiais (empilhadeiras, paleteiras, pontes rolantes etc.), núcleo do código 'equipamentos de movimentação'.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-14-92", youtubeId: "3GXwLt8EFDs", title: `Logística - Movimentação e Armazenagem - Aula 01`, channel: `EaD IFPI`, subjectSlug: "especificas", syllabusCodes: ["AC-14"], topicSlug: "ac-14-manuseio-materiais", justification: `Aula institucional (Instituto Federal do Piauí) sobre princípios de movimentação e armazenagem de materiais, aprofundando os 'princípios de movimentação eficiente' citados no código.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-15-93", youtubeId: "DDNQD6_GWo4", title: `Embalagem na Logística`, channel: `Canal de Logística`, subjectSlug: "especificas", syllabusCodes: ["AC-15"], topicSlug: "ac-15-embalagem", justification: `Aula direta sobre tipos e funções de embalagem na logística, núcleo do código. Usado como principal após 3+ buscas com termos distintos não localizarem aula equivalente nos canais prioritários de concursos (Estratégia Concursos, CPWS, Adriane Fauth - que não cobre logística).`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-15-94", youtubeId: "F1puXxR2C9g", title: `Logística de Transportes - Aula: Cargas Perigosas (Aula 1) - Concursos Petrobras e Transpetro | CPWS`, channel: `CPWS - Concursos Petrobras e Transpetro`, subjectSlug: "especificas", syllabusCodes: ["AC-15"], topicSlug: "ac-15-embalagem", justification: `[CORRIGIDO 2026-08-20: papel reclassificado de complementar_questoes para complementar_revisao após verificação — o título 'Aula: Cargas Perigosas (Aula 1)' indica aula expositiva/teórica estruturada de um curso, não sessão de resolução de questões; recolocado como 3º vídeo (revisão/cobertura do subtema 'segurança no transporte', não coberto pelos outros dois) para não duplicar o papel complementar_aprofundamento já usado neste código.] Aula de curso de concursos Petrobras/Transpetro sobre transporte de cargas perigosas, cobrindo de forma extensa o subtema 'segurança no transporte' do código AC-15, que os outros dois vídeos não tratam.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-16-95", youtubeId: "df_0zEB5L1I", title: `Logística de Transporte - Aula: Lei 13.303/2016 – Do procedimento de Licitação | CPWS Concursos`, channel: `CPWS - Concursos Petrobras e Transpetro`, subjectSlug: "especificas", syllabusCodes: ["AC-16"], topicSlug: "ac-16-gestao-compras", justification: `Aula específica e vigente sobre a Lei 13.303/2016 (regime de licitações e contratos de estatais como Transpetro), tratando do procedimento licitatório citado explicitamente no código AC-16. NÃO é baseada na Lei 8.666/1993 (revogada).`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-16-96", youtubeId: "KuycQPQwYZ0", title: `Curso Completo de Licitações e Contratos - Lei 14.133/2021 - Prof. Herbert Almeida`, channel: `Estratégia Concursos`, subjectSlug: "especificas", syllabusCodes: ["AC-16"], topicSlug: "ac-16-gestao-compras", justification: `Curso completo e vigente sobre a Nova Lei Geral de Licitações (Lei 14.133/2021), a segunda lei citada explicitamente no código AC-16, ministrado por professor de referência da Estratégia Concursos. NÃO trata da Lei 8.666/1993 revogada.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-16-97", youtubeId: "wcX4nhztmmg", title: `Téc. de Suprimento de Bens e Serviços: Lei 13.303/2016 (Aula 1) - Concursos Petrobras CPWS`, channel: `CPWS - Concursos Petrobras e Transpetro`, subjectSlug: "especificas", syllabusCodes: ["AC-16"], topicSlug: "ac-16-gestao-compras", justification: `Revisita a Lei 13.303/2016 sob a ótica de suprimento de bens e serviços (compras), reforçando o mesmo diploma legal vigente citado no código, a partir de um ângulo aplicado e prático de concursos de estatal.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-17-98", youtubeId: "KuycQPQwYZ0", title: `Curso Completo de Licitações e Contratos - Lei 14.133/2021 - Prof. Herbert Almeida`, channel: `Estratégia Concursos`, subjectSlug: "especificas", syllabusCodes: ["AC-17"], topicSlug: "ac-17-gestao-contratos", justification: `Mesmo curso completo do professor Herbert Almeida (Estratégia Concursos) citado em AC-16, cujo conteúdo inclui capítulo específico sobre contratos administrativos da Lei 14.133/2021 (formalização, execução, fiscalização, alteração/aditivos), cobrindo o núcleo de 'ciclo de vida do contrato' e 'gestão de riscos e aditivos' do código.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-17-99", youtubeId: "df_0zEB5L1I", title: `Logística de Transporte - Aula: Lei 13.303/2016 – Do procedimento de Licitação | CPWS Concursos`, channel: `CPWS - Concursos Petrobras e Transpetro`, subjectSlug: "especificas", syllabusCodes: ["AC-17"], topicSlug: "ac-17-gestao-contratos", justification: `Mesma aula CPWS citada em AC-16; aborda o procedimento licitatório de estatais que antecede e fundamenta a formalização e gestão dos contratos no regime da Lei 13.303/2016, aplicável ao ciclo de vida contratual em empresas como a Transpetro.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-17-100", youtubeId: "EO-WGTYYAqA", title: `Minicurso de GESTÃO DE CONTRATOS para CONCURSOS - Lei 14.133/21 - AULA 01 - Professor Franco`, channel: `JUS POLIS`, subjectSlug: "especificas", syllabusCodes: ["AC-17"], topicSlug: "ac-17-gestao-contratos", justification: `Minicurso dedicado especificamente a 'Gestão de Contratos' (não licitações em geral) sob a Lei 14.133/2021, complementando as duas aulas anteriores (focadas majoritariamente em licitação) com um recorte de revisão orientado ao ciclo de vida, fiscalização e alteração/aditivos contratuais citados no código AC-17. Encontrado após pesquisa adicional dedicada especificamente a este gap (buscas: 'gestão e fiscalização de contratos Lei 14.133 aula Estratégia OR Gran Cursos', confirmando também um vídeo do mesmo tema no canal 'Contabilidade e Direito' e outro do 'Professor Mazziotti' descartados por não serem de canal de concursos ou por tratarem só de licitação, não de gestão de contratos).`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-18-101", youtubeId: "QIB18HYMdok", title: `Informática para Concursos 2026 - AULA 1 - Windows 11 - Prof. Alan Souza`, channel: `Prof. Alan Souza`, subjectSlug: "especificas", syllabusCodes: ["AC-18"], topicSlug: "ac-18-fundamentos-computacao", justification: `Primeira aula de série 2026 sobre o sistema operacional Windows, cobrindo fundamentos de hardware/software e introdução ao Windows 11, específico para concursos e atualizado para 2026.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-18-102", youtubeId: "R_56fkYwmfY", title: `Informática para Concursos 2026 - AULA 8 - Windows 11 - Prof. Alan Souza`, channel: `Prof. Alan Souza`, subjectSlug: "especificas", syllabusCodes: ["AC-18"], topicSlug: "ac-18-fundamentos-computacao", justification: `Aula da mesma série 2026 dedicada aos acessórios/utilitários do Windows 11, aprofundando o subtema 'utilitários, aplicativos e manipulação de arquivos' do código.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-18-103", youtubeId: "8SmLcUatOmA", title: `Questões de Informática para Concursos - Sistemas Operacionais`, channel: `Prof. Marcelo Narciso`, subjectSlug: "especificas", syllabusCodes: ["AC-18"], topicSlug: "ac-18-fundamentos-computacao", justification: `Resolução de questões de concurso sobre sistemas operacionais, servindo de treino de questões objetivas para o tema Windows/sistemas operacionais do código.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-19-104", youtubeId: "hB73XLR24dQ", title: `Informática para Concursos 2026 - AULA 1 - MS WORD 365 - Prof. Alan Souza`, channel: `Prof. Alan Souza`, subjectSlug: "especificas", syllabusCodes: ["AC-19"], topicSlug: "ac-19-aplicativos-comerciais", justification: `Aula 2026 sobre Microsoft Word (versão 365/nuvem, equivalente atual ao Office 2024 mencionado no edital), cobrindo edição de textos citada no código. Observação: é Word 365, não literalmente 'Office 2024', mas trata da versão vigente do aplicativo.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-19-105", youtubeId: "VFQ6BqDDePM", title: `Aula de Informática do zero: Word e Excel - AlfaCon`, channel: `AlfaCon`, subjectSlug: "especificas", syllabusCodes: ["AC-19"], topicSlug: "ac-19-aplicativos-comerciais", justification: `Aula longa e completa cobrindo Word e Excel (planilhas) para concursos, aprofundando o subtema 'planilhas' do código, que a aula principal (focada em Word) não cobre em profundidade.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-19-106", youtubeId: "d1NGqMxkp1g", title: `Informática para Concursos - PowerPoint - AlfaCon`, channel: `AlfaCon`, subjectSlug: "especificas", syllabusCodes: ["AC-19"], topicSlug: "ac-19-aplicativos-comerciais", justification: `Revisão objetiva e curta sobre PowerPoint (material multimídia), cobrindo o subtema 'material escrito e multimídia' do código de forma resumida; vídeo mais antigo mas conceitos de interface do PowerPoint têm baixa obsolescência.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-20-107", youtubeId: "6G_onNf0IMc", title: `Informática para Concursos - Aula 03.01 - Internet x Intranet x Extranet - Internet`, channel: `Professor Alê`, subjectSlug: "especificas", syllabusCodes: ["AC-20"], topicSlug: "ac-20-internet-intranet", justification: `Aula específica sobre o conceito de Internet dentro de uma série comparativa Internet x Intranet x Extranet, cobrindo diretamente o núcleo conceitual do código.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-20-108", youtubeId: "8VeJYDIBqME", title: `Informática para Concursos - Aula 03.02 - Internet x Intranet x Extranet - Intranet`, channel: `Professor Alê`, subjectSlug: "especificas", syllabusCodes: ["AC-20"], topicSlug: "ac-20-internet-intranet", justification: `Continuação da série do Professor Alê, aprofundando especificamente o conceito de Intranet, segundo pilar do código AC-20.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-20-109", youtubeId: "vmNii8_xtqA", title: `500 Questões de Informática [Navegadores] - Prof. Alan Souza`, channel: `Prof. Alan Souza`, subjectSlug: "especificas", syllabusCodes: ["AC-20"], topicSlug: "ac-20-internet-intranet", justification: `Bateria de questões comentadas especificamente sobre navegadores de internet, cobrindo o subtema 'principais navegadores' do código em formato de treino de questões.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-21-110", youtubeId: "PxgYsfzLaoo", title: `Segurança da Informação - aula de Informática para Concursos - AO VIVO`, channel: `AlfaCon`, subjectSlug: "especificas", syllabusCodes: ["AC-21"], topicSlug: "ac-21-seguranca-informacao-lgpd", justification: `Aula completa e extensa sobre noções de segurança da informação (conceitos, princípios, ataques, mecanismos de proteção) para concursos, núcleo do código AC-21.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-21-111", youtubeId: "hnx-wS3i1TY", title: `Lei Geral de Proteção de Dados - LGPD (13.709/18) - Professor Luciano Franco`, channel: `JUS POLIS`, subjectSlug: "especificas", syllabusCodes: ["AC-21"], topicSlug: "ac-21-seguranca-informacao-lgpd", justification: `Aula dedicada e recente especificamente à Lei nº 13.709/2018 (LGPD) e suas alterações, segundo pilar explícito do código AC-21, com riqueza de detalhes sobre a lei vigente.`, verifiedAt: VERIFIED_AT },
  { id: "video-ac-21-112", youtubeId: "C8ZTng3xRiA", title: `Segurança da Informação p Concursos | Confidencialidade Integridade Disponibilidade e Autenticidade`, channel: `ROMILTON JÚNIOR`, subjectSlug: "especificas", syllabusCodes: ["AC-21"], topicSlug: "ac-21-seguranca-informacao-lgpd", justification: `Revisão curta e objetiva dos princípios (pilares) da segurança da informação (CID + Autenticidade), reforçando de forma resumida os conceitos centrais do código.`, verifiedAt: VERIFIED_AT },
];

export const VIDEO_COUNT_BY_SUBJECT = VIDEO_LESSONS.reduce<Record<string, number>>((acc, v) => {
  acc[v.subjectSlug] = (acc[v.subjectSlug] ?? 0) + 1;
  return acc;
}, {});

export function getVideosForSyllabusCodes(codes: string[]): VideoLesson[] {
  return VIDEO_LESSONS.filter((v) => v.syllabusCodes.some((c) => codes.includes(c)));
}
